import Head from 'next/head'
import { useState } from 'react'
import FormPopUp from '../components/FormPopUp/FormPopUp'
import Hero from '../components/Hero/Hero'
import Modal from '../components/Modal/Modal'

import * as contentful from 'contentful';
import SwiperNews from '../components/SwiperNews/SwiperNews'


export default function Home({newsList}) {

  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <Head>
        <title>DonNetwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero setIsOpen={setIsOpen}/>

      <Modal modalStatus={isOpen} setModalStatus={setIsOpen}>
        <FormPopUp setIsOpen={setIsOpen}/>
      </Modal>

      <div className="mt-10">
        <SwiperNews list={newsList}/>
      </div>


      <div className='test'></div>

    </div>

  )
}

// created client
const client = contentful.createClient({
  space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE,
  accessToken: process.env.NEXT_PUBLIC_API_ACCESS_TOKEN,
});

// get data from contentful
export async function getStaticProps() {

  try {
    const data = await client.getEntries({
      content_type: 'donNetworkNews',
    })

    console.log("data------- ", data)

    return {
      props: {
        newsList: data
      }
    }
  }
  catch {
    return {
      props: {
        newsList: null
      }
    }
  }

}
