import Head from 'next/head'
import { useState } from 'react'
import FormPopUp from '../components/FormPopUp/FormPopUp'
import Hero from '../components/Hero/Hero'
import Modal from '../components/Modal/Modal'

import * as contentful from 'contentful';


export default function Home() {

  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <Head>
        <title>DonNetwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero setIsOpen={setIsOpen}/>

      <Modal modalStatus={isOpen} setModalStatus={setIsOpen}>
        <FormPopUp setIsOpen={setIsOpen}/>
      </Modal>

      <div className='test'></div>

    </div>

  )
}

// created client
const client = contentful.createClient({
  space: 'em36vxt5gdit',
  accessToken: '1jH1Zp2NGpmv2mDk_QR6-duBXdxgxecrTpkuNwsGsdE',
});

// get data from contentful
export async function getStaticProps() {

  const data = await client.getEntry('3AVRVdIxocAEEeNYtHOUDB')

  console.log('data', data)

  return {
    props: {
      title: data.fields.title,
      updatedAt: data.sys.updatedAt
    }
  }

}
